Improve use of All() and speedup Unmapped Folder matching
Sonarr/Sonarr pull request #3992
Opened 2020-10-02 03:32 UTC by Qstick

#### Database Migration
NO

#### Description

- Add `AllSeriesPaths` Method
- Use `AllSeriesPaths` in lieu of `All()` in HealthChecks, Diskspace, RootFolderService
- Only call All() (AllSeriesPaths) once for `AllWithUnmappedFolders` instead of for each folder

#### Todos
- [x] Tests

2020-10-04 04:09 UTC, Qstick commented
A few stats on a couple cases I ran for this:

Commit 1
```
With 85 Series (small case) - GetAll vs GetAllPaths
[Info] RootFolderCheck: GetAll time: 23ms
[Info] RootFolderCheck: GetAllPaths time: 7ms
```

Commit 2
```
27 Root Folders, ~450 Series

Before
[Debug] Api: [GET] /api/v3/rootFolder: 200.OK (8040 ms)

After
[Debug] Api: [GET] /api/v3/rootFolder: 200.OK (195 ms)
```

2020-10-10 03:21 UTC, markus101 requested changes
Just some small things to clean up, then I think we're good.

2020-10-10 03:21 UTC, markus101 commented on src/NzbDrone.Core/Tv/SeriesService.cs
> +            return _seriesRepository.AllSeriesPaths().ToList();
`_seriesRepository.AllSeriesPaths()` already returns a list.

2020-10-10 23:25 UTC, Qstick commented
@markus101 Fixed

2020-10-18 21:59 UTC, merged