Only allow one of the two checkboxes around empty folders to be checked at time.
Sonarr/Sonarr pull request #4192
Opened 2020-12-24 16:50 UTC by RobinDadswell

#### Database Migration
NO

#### Description
Both "Create empty series folders" and "Delete empty folders" can be active at the same time - this will- disable them both from being active. 

![image](https://user-images.githubusercontent.com/19610103/103099861-0b684e80-4608-11eb-8f42-aa678f099bc6.png)

2020-12-24 19:14 UTC, markus101 requested changes
We should add validation in the API side as well, that’ll direct users to fix their settings if they attempt to save them, even if they haven’t altered them.

2020-12-24 19:15 UTC, Taloth commented
As mentioned on discord, the scenario of both of them being checked it already handled internally. So we do not need to enforce it.

2020-12-26 19:05 UTC, markus101 commented
Based on the conversations on discord it doesn't seem like we really need this, but I'm wondering what the original driving factor was.

2020-12-28 00:02 UTC, RobinDadswell commented
The driving factor was that I noticed there was the ability to have both settings selected which could prove confusing to users as the default behaviour isn't clear if both are selected (although it is more clear after Taloth explained it in Discord) - the consensus based on our conversations in Discord (As I am reading it) was that the tick box guard makes sense - the API validation is the bit that isn't needed

[Link to last message from Taloth on the subject](https://discord.com/channels/383686866005917708/383686866475548674/791755176339832872)

2021-01-14 20:24 UTC, thezoggy commented
these only invalidate each other for new->future state but can be useful to normalize previous folder states.
aka you had empty folder before using sonarr, having the option check to delete empty would clean it up.

2021-01-30 22:42 UTC, closed without merging