Fixed: Parser Improvements
Sonarr/Sonarr pull request #4202
Opened 2020-12-30 01:17 UTC by bakerboy448

#### Database Migration
NO

#### Description
Additional handling for various parser issues; see linked GHI

#### Todos
- [X ] Tests
- [ ] Wiki Updates -N/A

#### Issues Fixed or Closed by this PR

* Fixes #4198
* Fixes #4199

2020-12-30 17:53 UTC, markus101 requested changes
Please update the commit messages to close the individual issues they address.

The quality parsing change should be renamed to: 
Fixed: Parsing of 4Kto1080p as 1080p

2020-12-30 17:53 UTC, markus101 commented on src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
> +        [TestCase("The.Mandalorian.2019.S02E07.Chapter.15.The.Believer.4Kto1080p.DSNYP.Webrip.x265.10bit.EAC3.5.1.Atmos.GokiTAoE", false)]
Please replace the series title with the generic `Series.Title`

2021-01-02 18:32 UTC, markus101 requested changes
he commits still need to be updated to include the GHIs they address.

2021-01-02 18:34 UTC, bakerboy448 commented
Just append the GHI # e.g  “(#XXXX)” to the commit messages, or what specifically are you looking for?

2021-01-02 18:56 UTC, markus101 commented
Yeah the typical format is:

```
Fixed: xyz

Closes #n
```

Example commit: https://github.com/Sonarr/Sonarr/commit/e5e86680c8f99687d3b95765be1c414cd1090191

2021-01-02 23:48 UTC, bakerboy448 commented
@markus101 should be good now!  Learn something new every PR :D

2021-01-03 06:08 UTC, merged