updated to include number of files
Sonarr/Sonarr pull request #4227
Opened 2021-01-06 16:43 UTC by RobinDadswell

#### Database Migration
NO

#### Description
Adds a box on series info to show the number of files
![image](https://user-images.githubusercontent.com/19610103/103795764-4a51c780-503e-11eb-8237-0b21bb6e0f26.png)

#### Issues Fixed or Closed by this PR

* #4203

2021-01-06 20:54 UTC, RobinDadswell commented
Updated to now look like
![image](https://user-images.githubusercontent.com/19610103/103818949-6155e100-5061-11eb-8477-316d54a754d7.png)

2021-01-09 20:38 UTC, markus101 requested changes
Code looks good, but I find the tooltip blends in too much with the labels below. I'm not sure if we want to inverse the tooltip (dark text or lighter background) or more the tooltip above. @Taloth thoughts?

2021-01-09 20:41 UTC, Taloth commented
Afaik Robin is still moving the code to inside Label.js so it's more global.

It blends a bit in the background, but it doesn't need to 'pop'. The original tooltip is inverted. However this is more in line with the other tooltips like Links. I'm ok with a different color scheme.

2021-01-09 22:14 UTC, RobinDadswell commented
> Afaik Robin is still moving the code to inside Label.js so it's more global.
> 
> It blends a bit in the background, but it doesn't need to 'pop'. The original tooltip is inverted. However this is more in line with the other tooltips like Links. I'm ok with a different color scheme.

I have paused on that temporarily as work has started to get busy which means I am relaxing heavily in the evenings. 

The colour scheme is the same as the links tooltip as per the comment from Taloth

2021-01-14 20:20 UTC, thezoggy commented
is this media files or files in the folder? (which could include a bit more  because of subs/metadata/etc)

2021-01-14 20:21 UTC, markus101 commented
Media files (same as the size is based on the number of media files).

2021-01-14 20:25 UTC, thezoggy commented
> 
> 
> Media files (same as the size is based on the number of media files).

then, just show the number of files with the size to group common context ?

2021-01-15 20:46 UTC, RobinDadswell commented
> then, just show the number of files with the size to group common context ? (which it actually does show it already on the size as a tooltip) - that's what I am doing; but it's about converting the logic from tooltip and making it work across all other popups like that.

2021-01-15 23:15 UTC, thezoggy commented
quick mockup of what I was talking about:
![sonarr](http://zoggy.net/firefox_2021-01-15_17-15-15.png)

2021-01-15 23:52 UTC, Taloth commented
We don't want to add more tags or make existing ones bigger. The point here is to make sure the tooltips work on touch devices, and that's it.

2021-01-18 02:12 UTC, austinwbest commented
Still think this should be n/n and not just the amount of files. 50/100 episodes (same concept as the index)

2021-01-30 23:09 UTC, markus101 requested changes
After playing with the other options I think the styling mostly works, just a change to the text.

I think only showing episode files makes sense in this case given episodes without files don't contribute to the size on disk.

Let's get this landed after the small fixups and we can look at refactoring the rest at another time.

2021-01-30 23:09 UTC, markus101 commented on frontend/src/Series/Details/SeriesDetails.css
> +  color: #e1e2e3;
I think `color: $white` works a bit better, though I think it's better in `Tooltip.css` in the `&.inverse` section:

```
&.inverse {
  background-color: $themeDarkColor;
  box-shadow: 0 5px 10px $popoverShadowInverseColor;
  color: $white;
}
```

Also looks like these are in the wrong order and failing in CI.

2021-02-03 19:09 UTC, RobinDadswell commented
@markus101  ready for another go!

2021-02-07 03:15 UTC, merged