Mediainfo hdr
Sonarr/Sonarr pull request #4278
Opened 2021-01-23 04:02 UTC by Matty666

#### Database Migration
NO

#### Description
This PR is to address issue #4276 where Dolby Vision HDR was not being picked up by sonarr in the media info formatting for VideoDynamicRange

I updated mediainfo library windows and mac to 20.09 and added `VideoHdrFormat` and `VideoHdrFormatCompatibility` properties to the `MediaInfoModel`.

Adjusted `MediaInfoFormatter.FormatVideoDynamicRange` to return HDR if the VideoHdrFormat field is not empty.

This should handle older media info schemas by defaulting the properties to empty, and the formatter will just assume SDR

#### Issues Fixed or Closed by this PR
#4276

2021-01-24 08:39 UTC, markus101 requested changes
I'll do some testing, but some minor things to start.

2021-01-24 08:39 UTC, markus101 commented on src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
> +            return VideoDynamicRangeSdr;
Just `return ""` here

2021-01-24 08:39 UTC, markus101 commented on src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatVideoDynamicRangeFixture.cs
> +
remove empty line

2021-01-24 08:39 UTC, markus101 commented on src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatVideoDynamicRangeFixture.cs
> +
remove empty line

2021-02-03 01:19 UTC, merged

2021-11-14 09:30 UTC, HitcherUK commented
Just started getting DV episodes myself and found the HDR tag wasn't being added for some shows so I Googled it and ended up here.

Here's the relevant media info -

```General
Unique ID                                : 323339236286035081249625431881342127732 (0xF340DF2A14C6A6CF3985873DF27E0E74)
Complete name                            : Z:\tvshows-dolby-vision\The Morning Show\Season 02\The Morning Show - S02E02 - It’s Like the Flu - [WEBDL-2160P] [HDR].mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 9.31 GiB
Duration                                 : 52 min 10 s
Overall bit rate                         : 25.5 Mb/s
Writing application                      : mkvmerge v59.0.0 ('Shining Star') 64-bit
Writing library                          : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 52 min 10 s
Bit rate                                 : 24.3 Mb/s
Width                                    : 3 840 pixels
Height                                   : 1 920 pixels
Display aspect ratio                     : 2.000
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.137
Stream size                              : 8.84 GiB (95%)
Language                                 : English
Default                                  : Yes
Forced                                   : No```

Should I open a new issue?

Thanks.

2021-11-14 09:59 UTC, Matty666 commented
@HitcherUK what version of sonarr are you using?

This PR adds code that looks at the HDR format media info field and if its present and not empty will assume its an HDR file.

Is your example filename generated by Sonarr?

`Z:\tvshows-dolby-vision\The Morning Show\Season 02\The Morning Show - S02E02 - It’s Like the Flu - [WEBDL-2160P] [HDR].mkv`

2021-11-14 10:11 UTC, HitcherUK commented
I added the `[HDR]` myself.

```]Version
3.0.6.1373
Package Version
3.0.6.1373-ls217 by linuxserver.io
```

2021-11-14 10:23 UTC, Matty666 commented
is it all DV files or just this one?

Can you provide the relevant output from `mediainfo --output=JSON -f <file>` , don't need everything, just the object that has `"@type": "Video",` that includes all the `HDR_*` properties

2021-11-14 14:52 UTC, HitcherUK commented
I got this using the advanced mode in MediaInfo. Hopefully this it's what you want.

```
Video
Count                                    : 379
Count of stream of this kind             : 1
Kind of stream                           : Video
Kind of stream                           : Video
Stream identifier                        : 0
StreamOrder                              : 0
ID                                       : 1
ID                                       : 1
Unique ID                                : 8597467595372641648
Format                                   : HEVC
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format/Url                               : http://www.itu.int
Commercial name                          : HEVC
Format profile                           : Main 10@L5@High
HDR format                               : Dolby Vision
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
HDR_Format_Commercial                    : Dolby Vision
HDR_Format_Version                       : 1.0
HDR_Format_Profile                       : dvhe.05
HDR_Format_Level                         : 06
HDR_Format_Settings                      : BL+RPU
Internet media type                      : video/H265
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 3188644.000000
Duration                                 : 53 min 8 s
Duration                                 : 53 min 8 s 644 ms
Duration                                 : 53 min 8 s
Duration                                 : 00:53:08.644
Duration                                 : 00:53:09;11
Duration                                 : 00:53:08.644 (00:53:09;11)
Bit rate                                 : 24902634
Bit rate                                 : 24.9 Mb/s
Width                                    : 3840
Width                                    : 3 840 pixels
Height                                   : 1920
Height                                   : 1 920 pixels
Sampled_Width                            : 3840
Sampled_Height                           : 1920
Pixel aspect ratio                       : 1.000
Display aspect ratio                     : 2.000
Display aspect ratio                     : 2.000
Frame rate mode                          : CFR
Frame rate mode                          : Constant
Frame rate                               : 23.976
Frame rate                               : 23.976 (24000/1001) FPS
FrameRate_Num                            : 24000
FrameRate_Den                            : 1001
Frame count                              : 76451
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Chroma subsampling                       : 4:2:0
Bit depth                                : 10
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.141
Delay                                    : 0
Delay                                    : 00:00:00.000
Delay, origin                            : Container
Delay, origin                            : Container
Stream size                              : 9925704618
Stream size                              : 9.24 GiB (97%)
Stream size                              : 9 GiB
Stream size                              : 9.2 GiB
Stream size                              : 9.24 GiB
Stream size                              : 9.244 GiB
Stream size                              : 9.24 GiB (97%)
Proportion of this stream                : 0.96970
Default                                  : Yes
Default                                  : Yes
Forced                                   : No
Forced                                   : No
```

2021-11-14 14:56 UTC, HitcherUK commented
This is from an episode that correctly gets tagged as `HDR`

```
Video
Count                                    : 380
Count of stream of this kind             : 1
Kind of stream                           : Video
Kind of stream                           : Video
Stream identifier                        : 0
StreamOrder                              : 0
ID                                       : 1
ID                                       : 1
Format                                   : HEVC
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format/Url                               : http://www.itu.int
Commercial name                          : HEVC
Format profile                           : Main 10@L5@High
HDR format                               : Dolby Vision
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
HDR_Format_Commercial                    : Dolby Vision
HDR_Format_Version                       : 1.0
HDR_Format_Profile                       : dvhe.05
HDR_Format_Level                         : 06
HDR_Format_Settings                      : BL+RPU
Internet media type                      : video/H265
Codec ID                                 : dvhe
Codec ID/Info                            : High Efficiency Video Coding with Dolby Vision
Duration                                 : 3332120
Duration                                 : 55 min 32 s
Duration                                 : 55 min 32 s 120 ms
Duration                                 : 55 min 32 s
Duration                                 : 00:55:32.120
Duration                                 : 00:55:32;23
Duration                                 : 00:55:32.120 (00:55:32;23)
Bit rate                                 : 24364568
Bit rate                                 : 24.4 Mb/s
Width                                    : 3840
Width                                    : 3 840 pixels
Height                                   : 1920
Height                                   : 1 920 pixels
Sampled_Width                            : 3840
Sampled_Height                           : 1920
Pixel aspect ratio                       : 1.000
Display aspect ratio                     : 2.000
Display aspect ratio                     : 2.000
Rotation                                 : 0.000
Frame rate mode                          : CFR
Frame rate mode                          : Constant
Frame rate                               : 23.976
Frame rate                               : 23.976 (24000/1001) FPS
FrameRate_Num                            : 24000
FrameRate_Den                            : 1001
Frame count                              : 79891
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Chroma subsampling                       : 4:2:0
Bit depth                                : 10
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.138
Stream size                              : 10148219775
Stream size                              : 9.45 GiB (97%)
Stream size                              : 9 GiB
Stream size                              : 9.5 GiB
Stream size                              : 9.45 GiB
Stream size                              : 9.451 GiB
Stream size                              : 9.45 GiB (97%)
Proportion of this stream                : 0.96912
Default                                  : Yes
Default                                  : Yes
Alternate group                          : 1
Alternate group                          : 1
Encoded date                             : UTC 2021-10-22 14:10:22
Tagged date                              : UTC 2021-10-22 14:11:52
Codec configuration box                  : hvcC+dvcC
```

2021-11-14 14:59 UTC, HitcherUK commented
Just realised that it seems to be the MKV versions that aren't getting tagged correctly whereas the MP4 ones are.

2021-11-19 22:45 UTC, Matty666 commented
@HitcherUK Can you post your `Settings` | `Media Management` | `Standard Episode Format` setting?

2021-11-20 00:20 UTC, HitcherUK commented
Sure -

`{Series Title} - S{season:00}E{episode:00} - {Episode Title} - { [QUALITY FULL]}{ [MediaInfo VideoDynamicRange]}`

2021-11-20 02:27 UTC, Matty666 commented
@HitcherUK i'm struggling to reproduce the issue. I've tried both mkv and mp4 files with DV and they all tag the filename correctly using your epsiode format. If `HDR format` is present in the media info (as it is in your 2 examples), it's treated as an HDR file.

2021-11-20 09:58 UTC, HitcherUK commented
No problem, thanks for checking.