Add logo to loading page
Sonarr/Sonarr pull request #4311
Opened 2021-02-06 13:02 UTC by Snarkenfaugister

#### Database Migration
NO

#### Description
Add 48px logo to loading screen, above message.
![logo](https://user-images.githubusercontent.com/7644535/107118856-58aa3200-68cf-11eb-8894-e29f3724d2a5.png)

#### Issues Fixed or Closed by this PR

* #4304

2021-02-07 03:32 UTC, markus101 requested changes
Ready to ship once linting passes and CI is green.

2021-02-07 03:32 UTC, markus101 commented on frontend/src/Components/Page/LoadingPage.css
> +}
Stylelint is failing this due to the lack of newline at the end of the file.

2021-02-07 19:51 UTC, merged

2021-02-09 11:06 UTC, agneevX commented
This icon is low res on Retina displays.

2021-02-09 11:10 UTC, Taloth commented
should've been svg

2021-02-09 11:20 UTC, agneevX commented
Almost as if it exists here: https://github.com/Sonarr/Sonarr/blob/phantom-develop/Logo/Sonarr.svg?short_path=b0a7218