Persist AddNewSeries search settings in local cache.
Sonarr/Sonarr pull request #4312
Opened 2021-02-06 13:52 UTC by Snarkenfaugister

#### Database Migration
NO

#### Description
Persist `searchForCutoffUnmetEpisodes` and `searchForMissingEpisodes` setting values in local cache.

#### Issues Fixed or Closed by this PR

* #4245

2021-02-06 13:57 UTC, bakerboy448 commented
For your commits if you do 

“Fixed: Blah Blah Blah
<new line>
Closes #GHI”

once merged itll 1) show as fixed on the change log and 2) reference the GHI on the change log

Appreciate the help though!

(force push w/ lease if you reword the commits)

2021-02-07 02:55 UTC, markus101 requested changes
Just the default comment and then good to land.

2021-02-07 02:55 UTC, markus101 commented on frontend/src/Store/Actions/addSeriesActions.js
> +    searchForMissingEpisodes: true,
These should both default to false like they do currently.

2021-02-07 03:18 UTC, merged

2021-02-07 03:19 UTC, markus101 commented
Thanks!