1374 aria2
Sonarr/Sonarr pull request #4380
Opened 2021-03-14 14:26 UTC by LLeny

#### Database Migration
NO

#### Description
Initial Aria2 download client, give aria2 some love.

#### TODO
* [ ] Test torrent file dl

#### Issues Fixed or Closed by this PR

* #1374
* #4172

2021-03-27 19:07 UTC, markus101 requested changes
Untested and mostly just style and nits to address.

2021-03-27 19:07 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/Aria2/Aria2Containers.cs
> +        public string version;
Property name should start with a capital letter (for all these classes).

2021-03-27 19:07 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/Aria2/Aria2Torrent.cs
> +    public class Aria2Torrent
I don't see this class used anywhere, is this file needed?

2021-03-27 19:07 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/Aria2/Aria2.cs
> +            if (failures.HasErrors()) return;
New line before if.

2021-03-27 19:07 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/Aria2/Aria2Proxy.cs
> +using Newtonsoft.Json.Linq;
There are a bunch of unused namespaces.

2021-03-27 19:07 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/Aria2/Aria2.cs
> +            var statuses = _proxy.GetStatuses(Settings);
I think this should be renamed to torrents/GetTorrents, it'll be more obvious what it is at a glance, the proxy can handle the translation to Aria2 logic.

Particularly `foreach(var status in statuses)` is confusing, why am I looping through statuses and then getting a separate status from the status.

2021-03-27 19:07 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/Aria2/Aria2Proxy.cs
> +            return client;
Nit: new line before return

2021-03-27 19:07 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/Aria2/Aria2Settings.cs
> +        public string RPCPath { get; set; }
`RpcPath`

2021-03-27 19:07 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/Aria2/Aria2Settings.cs
> +        public bool UseSSL { get; set; }
`UseSsl`

2021-03-28 04:13 UTC, bakerboy448 commented
This will also require wiki updates[wiki updates](https://wiki.servarr.com/Template:Settings_download_clients_download_clients) 

let me know or write them up in markdown or media wiki and I can get those applied

2021-04-03 04:00 UTC, LLeny commented
> This will also require [wiki updates](https://wiki.servarr.com/Template:Settings_download_clients_download_clients)
> 
> let me know or write them up in markdown or media wiki and I can get those applied

Torrent Client Settings
```
* Secret token - RPC secret authorization token
```

Supported Clients
```
* Aria2
** Requires aria2 1.34.0 or higher
** Website: [https://aria2.github.io/ aria2]
```
Compatibility
```
| Aria2
|align="center"| -
|align="center"| -
|-
```

2021-04-22 23:46 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/Aria2/Aria2.cs
> +            //Aria2 doesn't support file deletion at this point: https://github.com/aria2/aria2/issues/728
You'll want to rebase (since this signature has changed) and use `DeleteItemData(DownloadClientItem item)` if `deleteData` is true.

2021-04-22 23:48 UTC, markus101 requested changes
This needs to be rebased to handle the updated signature for `RemoveItem` and left a comment on how to handle the deletion of the data.

2021-05-25 06:14 UTC, LLeny commented
Do you need anything more from me to go forward with it ?

2021-08-01 19:49 UTC, merged

2021-08-01 19:49 UTC, markus101 commented
Thanks for contributing.