Download station2
Sonarr/Sonarr pull request #4485
Opened 2021-05-09 23:32 UTC by twentynine78

#### Database Migration
NO

#### Description
Added compatibility with the new Download Station API 'SYNO.DownloadStation2.Task'.

This will resolve the compatibility issue with the new version of Synology Download Stations 3.8.16-3566.
If the new 'SYNO.DownloadStation2.Task' API is available, use it, otherwise use the old 'SYNO.DownloadStation.Task'.

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR

* Fixes #4388

2021-05-14 23:55 UTC, markus101 requested changes
Just a couple minor things, but tested and working well. Thanks!

2021-05-14 23:55 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV2.cs
> +            if (downloadDirectory.IsNotNullOrWhiteSpace())
Nit: new line before if

2021-05-14 23:55 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV2.cs
> +            if (downloadDirectory.IsNotNullOrWhiteSpace())
Nit: new line before if

2021-05-18 11:15 UTC, twentynine78 commented on src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV2.cs
> +            if (downloadDirectory.IsNotNullOrWhiteSpace())
Done.

2021-05-18 11:15 UTC, twentynine78 commented on src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV2.cs
> +            if (downloadDirectory.IsNotNullOrWhiteSpace())
Done.

2021-05-18 11:17 UTC, twentynine78 reviewed
Fix nits

2021-06-08 07:57 UTC, drloser123 commented
Hi, do you still plan to release this fix?
I'm currently using an old version of Download Station API and I'd like to know when it's safe to update.

2021-06-22 03:29 UTC, merged

2021-06-22 03:33 UTC, markus101 commented
Thanks for contributing!

2021-06-22 05:24 UTC, drloser123 commented
Thanks a lot!

2021-06-24 14:33 UTC, felho001 commented
Hi my sonnar Download station old version same not vork 3.8.15-3563 2 days ago and now update DS last version (3.8.16-3566.) but not solved. How can fix this?

2021-06-24 14:38 UTC, justin-robinson commented
> Hi my sonnar Download station old version same not vork 3.8.15-3563 2 days ago and now update DS last version (3.8.16-3566.) but not solved. How can fix this?

Make sure you're sonarr install is updating from develop and not main. or wait until this is merged into main

2021-06-24 14:39 UTC, felho001 commented
I use sonarr dev but not work

2021-06-24 14:40 UTC, markus101 commented
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

2021-06-24 14:41 UTC, felho001 commented
I use but no have information this issue

2021-06-30 20:46 UTC, Prime-Omega commented
Not sure if running into the same issues or not but I upgraded DSM 6 to DSM 7. Unfortunately that automatically caused my Download station to upgrade from version 3.8.16-3563 to 3.9.0-4600. The issue seems to be similar as before when I upgraded to 3.8.16-3566. Also not sure if it might help but Radarr is not affected by this issue, it still sends requests to download station just fine.

Trace logs:

`20-9-8 14:24:25.5|Debug|Api|[GET] /api/v3/health: 200.OK (4 ms)
20-9-8 14:24:25.5|Debug|Api|[PUT] /api/v3/config/host: 202.Accepted (466 ms)
20-9-8 14:24:26.3|Debug|Api|[GET] /api/v3/wanted/missing?page=1&pageSize=20&sortDirection=descending&sortKey=airDateUtc&monitored=true: 200.OK (59 ms)
20-9-8 14:24:26.3|Debug|Api|[GET] /api/v3/queue/details?episodeIds=13173&episodeIds=13360&episodeIds=13361&episodeIds=13362&episodeIds=13363&episodeIds=13182&episodeIds=13206&episodeIds=13207&episodeIds=13208&episodeIds=13209&episodeIds=13210&episodeIds=13211&episodeIds=13069&episodeIds=13070&episodeIds=13071&episodeIds=13072&episodeIds=13073&episodeIds=6070: 200.OK (7 ms)
20-9-8 14:24:27.2|Debug|DiskTransferService|Move [/series/Mad Men/Season 06/Mad Men S06e10 - A Tale of Two Cities.mkv] > [/recycle/Mad Men/Season 06/Mad Men S06e10 - A Tale of Two Cities.mkv]
20-9-8 14:24:30.6|Debug|Api|[POST] /api/v3/command: 201.Created (126 ms)
20-9-8 14:24:30.7|Debug|DownloadedEpisodesImportService|Processing path: /downloads/1/
20-9-8 14:24:30.7|Debug|Parser|Parsing string '1'
20-9-8 14:24:30.7|Debug|Parser|Unable to parse 1
20-9-8 14:24:30.7|Debug|DownloadedEpisodesImportService|Unknown Series 1
20-9-8 14:24:30.7|Debug|DownloadedEpisodesCommandService|Failed to import
20-9-8 14:24:30.9|Debug|Api|[GET] /api/v3/command: 200.OK (5 ms)
20-9-8 14:24:33.8|Debug|DownloadStationTaskProxy|Trying to get tasks
20-9-8 14:24:33.9|Debug|Parser|Parsing string 'Nintendo Gamecube ISO Library + Emulators'
20-9-8 14:24:33.9|Debug|Parser|Unable to parse Nintendo Gamecube ISO Library + Emulators
20-9-8 14:24:33.9|Debug|Parser|Parsing string 'Library Update Pack 71'
20-9-8 14:24:33.9|Debug|Parser|Episode Parsed. Library Update Pack - 071 
20-9-8 14:24:33.9|Debug|Parser|Language parsed: English
20-9-8 14:24:33.9|Debug|QualityParser|Trying to parse quality for Library Update Pack 71
20-9-8 14:24:33.9|Debug|Parser|Quality parsed: Unknown v1
20-9-8 14:24:33.9|Debug|Parser|Release Group parsed: 
20-9-8 14:24:33.9|Debug|ParsingService|No matching series Library Update Pack
20-9-8 14:24:33.9|Debug|Parser|Parsing string 'Horizon.Zero.Dawn-CODEX'
20-9-8 14:24:33.9|Debug|Parser|Unable to parse Horizon.Zero.Dawn-CODEX
20-9-8 14:24:33.9|Debug|Parser|Parsing string 'Wii-Pack 4 of 5'
20-9-8 14:24:33.9|Debug|Parser|Unable to parse Wii-Pack 4 of 5
20-9-8 14:24:33.9|Debug|Parser|Parsing string 'Wii-Pack 3 of 5'
20-9-8 14:24:33.9|Debug|Parser|Unable to parse Wii-Pack 3 of 5
20-9-8 14:24:33.9|Debug|Parser|Parsing string 'Android - only Paid - Week 30 2020 - APPS'
20-9-8 14:24:33.9|Debug|Parser|Episode Parsed. Android - only Paid - Week 30 - S20E20 
20-9-8 14:24:33.9|Debug|Parser|Language parsed: English
20-9-8 14:24:33.9|Debug|QualityParser|Trying to parse quality for Android - only Paid - Week 30 2020 - APPS
20-9-8 14:24:33.9|Debug|Parser|Quality parsed: Unknown v1
20-9-8 14:24:33.9|Debug|Parser|Release Group parsed: 
20-9-8 14:24:33.9|Debug|ParsingService|No matching series Android - only Paid - Week 30
20-9-8 14:24:33.9|Debug|Parser|Parsing string 'Step.Siblings.Caught.Jan.Jul.2020.XXX.H264.1080p.Spoogemonkey'
20-9-8 14:24:33.9|Debug|Parser|Episode Parsed. Step Siblings Caught Jan Jul - S20E20 
20-9-8 14:24:33.9|Debug|Parser|Language parsed: English
20-9-8 14:24:33.9|Debug|QualityParser|Trying to parse quality for Step.Siblings.Caught.Jan.Jul.2020.XXX.H264.1080p.Spoogemonkey
20-9-8 14:24:33.9|Debug|Parser|Quality parsed: HDTV-1080p v1
20-9-8 14:24:33.9|Debug|Parser|Release Group parsed: 
20-9-8 14:24:33.9|Debug|ParsingService|No matching series Step Siblings Caught Jan Jul
20-9-8 14:24:33.9|Debug|Parser|Parsing string 'Library Update Pack 84'
20-9-8 14:24:33.9|Debug|Parser|Episode Parsed. Library Update Pack - 084 
20-9-8 14:24:33.9|Debug|Parser|Language parsed: English
20-9-8 14:24:33.9|Debug|QualityParser|Trying to parse quality for Library Update Pack 84
20-9-8 14:24:33.9|Debug|Parser|Quality parsed: Unknown v1
20-9-8 14:24:33.9|Debug|Parser|Release Group parsed: 
20-9-8 14:24:33.9|Debug|ParsingService|No matching series Library Update Pack
20-9-8 14:24:33.9|Debug|Parser|Parsing string 'Nubiles.MFP.May.Jul.2020.XXX.H264.Spoogemonkey'
20-9-8 14:24:34.0|Debug|Parser|Episode Parsed. Nubiles MFP May Jul - S20E20 
20-9-8 14:24:34.0|Debug|Parser|Language parsed: English
20-9-8 14:24:34.0|Debug|QualityParser|Trying to parse quality for Nubiles.MFP.May.Jul.2020.XXX.H264.Spoogemonkey
20-9-8 14:24:34.0|Debug|Parser|Quality parsed: Unknown v1
20-9-8 14:24:34.0|Debug|Parser|Release Group parsed: 
20-9-8 14:24:34.0|Debug|ParsingService|No matching series Nubiles MFP May Jul
20-9-8 14:24:34.0|Debug|Parser|Parsing string 'Into.the.Night.S01E01.Sylvie.1080p.NF.WEB-DL.DDP5.1.x264-NTG'
20-9-8 14:24:34.0|Debug|Parser|Episode Parsed. Into the Night - S01E01 
20-9-8 14:24:34.0|Debug|Parser|Language parsed: English
20-9-8 14:24:34.0|Debug|QualityParser|Trying to parse quality for Into.the.Night.S01E01.Sylvie.1080p.NF.WEB-DL.DDP5.1.x264-NTG
20-9-8 14:24:34.0|Debug|Parser|Quality parsed: WEBDL-1080p v1
20-9-8 14:24:34.0|Debug|Parser|Release Group parsed: NTG
20-9-8 14:24:34.0|Debug|Parser|Parsing string 'Into the Night S01 1080p NF WEBRip X264 Ac3 SNAKE'
20-9-8 14:24:34.0|Debug|Parser|Episode Parsed. Into the Night - Season 01 
20-9-8 14:24:34.0|Debug|Parser|Language parsed: English
20-9-8 14:24:34.0|Debug|QualityParser|Trying to parse quality for Into the Night S01 1080p NF WEBRip X264 Ac3 SNAKE
20-9-8 14:24:34.0|Debug|Parser|Quality parsed: WEBRip-1080p v1
20-9-8 14:24:34.0|Debug|Parser|Release Group parsed: 
20-9-8 14:24:34.1|Debug|Parser|Parsing string 'Biohackers.S01E01.MULTi.1080p.WEB.x264-CiELOS'
20-9-8 14:24:34.1|Debug|Parser|Episode Parsed. Biohackers - S01E01 
20-9-8 14:24:34.1|Debug|Parser|Language parsed: English
20-9-8 14:24:34.1|Debug|QualityParser|Trying to parse quality for Biohackers.S01E01.MULTi.1080p.WEB.x264-CiELOS
20-9-8 14:24:34.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
20-9-8 14:24:34.1|Debug|Parser|Release Group parsed: CiELOS
20-9-8 14:24:34.1|Debug|Parser|Parsing string 'Biohackers.S01E03.MULTi.1080p.WEB.x264-CiELOS'
20-9-8 14:24:34.1|Debug|Parser|Episode Parsed. Biohackers - S01E03 
20-9-8 14:24:34.1|Debug|Parser|Language parsed: English
20-9-8 14:24:34.1|Debug|QualityParser|Trying to parse quality for Biohackers.S01E03.MULTi.1080p.WEB.x264-CiELOS
20-9-8 14:24:34.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
20-9-8 14:24:34.1|Debug|Parser|Release Group parsed: CiELOS
20-9-8 14:24:34.1|Debug|Parser|Parsing string 'Biohackers.S01E05.MULTi.1080p.WEB.x264-CiELOS'
20-9-8 14:24:34.1|Debug|Parser|Episode Parsed. Biohackers - S01E05 
20-9-8 14:24:34.1|Debug|Parser|Language parsed: English
20-9-8 14:24:34.1|Debug|QualityParser|Trying to parse quality for Biohackers.S01E05.MULTi.1080p.WEB.x264-CiELOS
20-9-8 14:24:34.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
20-9-8 14:24:34.1|Debug|Parser|Release Group parsed: CiELOS
20-9-8 14:24:34.1|Debug|Parser|Parsing string 'Biohackers.S01E04.MULTi.1080p.WEB.x264-CiELOS'
20-9-8 14:24:34.1|Debug|Parser|Episode Parsed. Biohackers - S01E04 
20-9-8 14:24:34.1|Debug|Parser|Language parsed: English
20-9-8 14:24:34.1|Debug|QualityParser|Trying to parse quality for Biohackers.S01E04.MULTi.1080p.WEB.x264-CiELOS
20-9-8 14:24:34.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
20-9-8 14:24:34.1|Debug|Parser|Release Group parsed: CiELOS
20-9-8 14:24:34.1|Debug|Parser|Parsing string 'Biohackers.S01E02.MULTi.1080p.WEB.x264-CiELOS'
20-9-8 14:24:34.1|Debug|Parser|Episode Parsed. Biohackers - S01E02 
20-9-8 14:24:34.1|Debug|Parser|Language parsed: English
20-9-8 14:24:34.1|Debug|QualityPar [...]

2021-06-30 20:49 UTC, bakerboy448 commented
@Prime-Omega  

1) please do not spam giant ?entire? log files via git... those are best shared via gist or pastebin
1b) only need the section around the error
2) PRs are not the replace to report issues.

2021-06-30 20:51 UTC, Prime-Omega commented
@bakerboy448 Give a man a second to edit his post will ya, not everyone is a github veteran. ;-) 

But you're right, I'll open a separate issue report.