Add optionnal seasonal anime search
Sonarr/Sonarr pull request #4728
Opened 2021-10-31 19:26 UTC by Bakeneko

#### Database Migration
NO

#### Description
Add an indexer setting to enable additionnal season format searches for anime.

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR
Related to #4153

2021-11-21 17:40 UTC, markus101 requested changes
Made a suggestion to improve the naming, but season anime searches should also search for standard season packs if that option is enabled.

2021-11-21 17:40 UTC, markus101 commented on src/NzbDrone.Core/Indexers/Fanzub/FanzubSettings.cs
> +        [FieldDefinition(1, Label = "Anime seasonal search", Type = FieldType.Checkbox, HelpText = "Add seasonal format search for Anime")]
This format is referred to as `Standard` everywhere else in Sonarr, it should be referred to that way in the setting as well, Season/Seasonal is far too easily confused with season pack searches.

Maybe: `Anime Standard Format Search` with the help text of `Also search for anime using the standard numbering format`

2021-11-29 17:41 UTC, Bakeneko commented
Added @markus101 suggestions and tests for request generators.

2022-01-23 21:12 UTC, markus101 commented
Made a small change and landed this in cee17483d97c1414b05b9f19729d612ef43934c2

2022-01-23 21:12 UTC, closed without merging

2022-06-19 18:54 UTC, reloxx13 commented
Heya,

when this checkbox is checked, shouldn't it also use t=TVSEARCH and not t=SEARCH for animes?

Standard uses tvsearch, while anime uses search, even when `Anime Standard Format Search` is checked.
When using t=SEARCH with anime as type, the results are ignoring the searched season and episode and returning alot of unwanted/unasked episodes. while changing t=TVSEARCH (i did it manual with the previos SEARCH api call) is returning the correct episodes.

if i set the anime serie to standard and add the anime category to the search categories of standard, im getting the correct episodes returned.