Fixed: Avoid download path check false positives for flood
Sonarr/Sonarr pull request #4827
Opened 2021-12-30 15:37 UTC by PearsonFlyer

(cherry picked from Radarr commit 7a859f340be3d0e82909e0f0d7260fb97409b4ee)

Authored by Qstick <qstick@gmail.com>

#### Database Migration
NO

#### Description
Solves issue where Flood download client was not passing in designated directory, causing a health warning.

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

* Fixes #4825

2021-12-30 17:39 UTC, markus101 commented
Two errors compiling:

```
M:\BuildAgent\work\2ad455abfc731aa2\src\NzbDrone.Core\Download\Clients\Flood\FloodProxy.cs(218,49): error CS0117: 'HttpMethod' does not contain a definition for 'Get' 
```
```
M:\BuildAgent\work\2ad455abfc731aa2\src\NzbDrone.Core\Download\Clients\Flood\Flood.cs(238,38): error CS1061: 'string' does not contain a definition for 'IsNotNullOrWhiteSpace' and no accessible extension method 'IsNotNullOrWhiteSpace' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)
```

2021-12-30 19:29 UTC, Qstick commented
Regarding the first error, we use native HttpMethod, so it's Get instead of GET as in the Sonarr abstraction.

On the second you man need a using @PearsonFlyer

2021-12-30 22:42 UTC, Qstick requested changes

2021-12-30 22:42 UTC, Qstick commented on src/NzbDrone.Core/Download/Clients/Flood/FloodProxy.cs
> +            contentsRequest.Method = HttpMethod.Get;
`GET` instead of `Get`

2021-12-30 22:42 UTC, Qstick commented on src/NzbDrone.Core/Download/Clients/Flood/Flood.cs
Add `using NzbDrone.Common.Extensions;` to this file

2022-01-15 19:45 UTC, Qstick approved these changes

2022-01-23 20:44 UTC, merged