Fix issues when setting up Emby in the Connect settings
Sonarr/Sonarr pull request #4855
Opened 2022-01-16 04:09 UTC by LASER-Yi

#### Database Migration
NO

#### Description
Fix issues when using Notification with Emby, the documentation can be found in [Emby's document](https://github.com/MediaBrowser/Emby/wiki/User-Authentication#authenticating-a-user)
<img width="469" alt="image" src="https://user-images.githubusercontent.com/23134797/149646961-389c7a32-7d1c-47b3-b895-8eecacd8dee8.png">

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR
NO

2022-01-16 04:12 UTC, bakerboy448 requested changes

2022-01-16 04:12 UTC, bakerboy448 commented on src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs
> +                ImageUrl = "https://raw.github.com/NzbDrone/NzbDrone/develop/Logo/64.png"
Sonarr/Sonarr

2022-01-16 04:15 UTC, LASER-Yi commented on src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs
> +                ImageUrl = "https://raw.github.com/NzbDrone/NzbDrone/develop/Logo/64.png"
Updated

2022-01-23 20:03 UTC, bakerboy448 commented
Note: likely breaking API changes for previous legacy versions

2022-01-23 21:07 UTC, markus101 commented
How long ago did this changes get implemented on Emby's side, does Jellyfin also support this new header and URL Base as well?

2022-01-23 22:41 UTC, Qstick commented
Based on what I could dig up, this happened before the JF fork (back in 2018 at some point). Though it was not well documented at all. It seems like JF supports it, but that was my biggest worry in letting this through. I think someone needs to test with JF

2022-02-11 21:03 UTC, closed without merging