Fixed: Escape Characters as needed for *znab queries
Sonarr/Sonarr pull request #4930
Opened 2022-03-04 21:41 UTC by bakerboy448

(cherry picked from commit 3fcc39596438beaf5e38de3fde4a83397940f80e)

#### Database Migration
NO

#### Description

#### Todos
- [ ] Help needed fixing failing text

#### Issues Fixed or Closed by this PR

* Fixes #4788

2022-04-06 00:20 UTC, markus101 requested changes
What feedback are you looking for before converting from a draft PR?

2022-04-06 00:20 UTC, markus101 commented on src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
> +            return Uri.EscapeDataString(newtitle);
Nit: Newline before return

2022-04-06 00:21 UTC, bakerboy448 commented
> What feedback are you looking for before converting from a draft PR?

Need some help getting the failing test to pass since as far as I can see it /should/ be passing.

2022-04-07 01:53 UTC, markus101 requested changes
You're missing params required to do any searching (commented where relevant), also left some comments to clean things up.

2022-04-07 01:53 UTC, markus101 commented on src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
> +
Extra new line

2022-04-07 01:53 UTC, markus101 commented on src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
> +            var results = Subject.GetSearchRequests(_singleEpisodeSearchCriteria);
Nit: New line before this line

2022-04-07 01:53 UTC, markus101 commented on src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
> +            _capabilities.SupportedTvSearchParameters = new[] { "q" };
This test is failing because it's missing `season` and `ep` parameters.

2022-04-07 01:53 UTC, markus101 commented on src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
> +            _capabilities.SupportedTvSearchParameters = new[] { "q" };
Same here: This test is failing because it's missing `season` and `ep` parameters.

2022-04-07 01:53 UTC, markus101 commented on src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
> +            var results = Subject.GetSearchRequests(_singleEpisodeSearchCriteria);
Same here: new line before variable.

2022-04-07 01:53 UTC, markus101 commented on src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
> +            return Uri.EscapeDataString(newtitle);
Also don't need to define a new variable.

```
title = title.Replace("+", " ");

return Uri.EscapeDataString(title);
```

2022-04-07 01:53 UTC, markus101 commented on src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
> +            _capabilities.TextSearchEngine = "raw";
This should be `TvTextSearchEngine`

2022-04-07 01:53 UTC, markus101 commented on src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
> +            _capabilities.TextSearchEngine = "sphinx";
Same here: this should be `TvTextSearchEngine`

2022-04-10 04:16 UTC, merged