Fixed: Clarify Qbit Content Path Error
Sonarr/Sonarr pull request #4967
Opened 2022-04-02 23:32 UTC by bakerboy448

#### Database Migration
NO

#### Description
title

#### Todos
- Tests
- Wiki Updates

#### Issues Fixed or Closed by this PR

*

2022-04-02 23:33 UTC, bakerboy448 commented on src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
> +                        item.Message = "Unable to Import. Path matches client download, perhaps 'Keep top-level folder' is disabled for this torrent or 'Torrent Content Layout' is NOT set to Original
```suggestion
                        item.Message = "Unable to Import. Path matches client download, perhaps 'Keep top-level folder' is disabled for this torrent or 'Torrent Content Layout' is NOT set to Original or Create Subfolder?";
```

2022-04-02 23:34 UTC, bakerboy448 commented on src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
> +                        item.Message = "Unable to Import. Path matches client download, perhaps 'Keep top-level folder' is disabled for this torrent or 'Torrent Content Layout' is NOT set to Original
```suggestion
                        item.Message = "Unable to Import. Path matches client base download directory, perhaps 'Keep top-level folder' is disabled for this torrent or 'Torrent Content Layout' is NOT set to Original or Create Subfolder?";
```

2022-04-06 00:21 UTC, markus101 requested changes

2022-04-06 00:21 UTC, markus101 commented on src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
> +                        item.Message = "Unable to Import. Path matches client base download directory, perhaps 'Keep top-level folder' is disabled for this torrent or 'Torrent Content Layout' is NOT
I think `perhaps` -> `possibly` is a little gentler, otherwise looks good.

2022-04-07 01:53 UTC, merged