Fixed: WebDL and WebRip Parsing
Sonarr/Sonarr pull request #5087
Opened 2022-07-19 16:26 UTC by bakerboy448

#### Database Migration
NO

#### Description
backport of various Radarr webdl/webrip parsing updates and sync the logic

#### Todos
- [x] Tests
- Wiki Updates

#### Issues Fixed or Closed by this PR

*

2022-07-30 03:08 UTC, markus101 requested changes

2022-07-30 03:08 UTC, markus101 commented on src/NzbDrone.Core/Parser/QualityParser.cs
> +                                                                (?<webdl>WEB[-_. ]DL(?:mux)?|WEBDL|AmazonHD|iTunesHD|MaxdomeHD|NetflixU?HD|WebHD|[. ]WEB[. ](?:[xh][ .]?26[45]|DDP?5[. ]1)|[. ](?-i:WEB
This test is now failing: `into.the.Series.s03e16.h264.720p-web-handbrake.mkv`

2022-07-30 03:08 UTC, markus101 commented on src/NzbDrone.Core/Parser/QualityParser.cs
> +                                                                (?<webdl>WEB[-_. ]DL(?:mux)?|WEBDL|AmazonHD|iTunesHD|MaxdomeHD|NetflixU?HD|WebHD|[. ]WEB[. ](?:[xh][ .]?26[45]|DDP?5[. ]1)|[. ](?-i:WEB
Shouldn't `\d{3,4}0p` be `\d{2,3}0p` to match `720p` or `1080p` and not `12340p`, that seems to fix the broken test as well as `Series.Title.S16.720p.WEB.DDP.5.1.H.264.PLEX` which should also pass.

2022-08-07 19:02 UTC, markus101 requested changes
The latest changes now break this test:

```
should_parse_webdl2160p_quality("Series.Title.2016.03.14.2160p.WEB.PROPER.h264-spamTV",True)
```

2022-08-07 19:42 UTC, bakerboy448 commented on src/NzbDrone.Core/Parser/QualityParser.cs
> +                                                                (?<webdl>WEB[-_. ]DL(?:mux)?|WEBDL|AmazonHD|iTunesHD|MaxdomeHD|NetflixU?HD|WebHD|[. ]WEB[. ](?:[xh][ .]?26[45]|DDP?5[. ]1)|[. ](?-i:WEB
```suggestion
                                                                (?<webdl>WEB[-_. ]DL(?:mux)?|WEBDL|AmazonHD|iTunesHD|MaxdomeHD|NetflixU?HD|WebHD|[. ]WEB[. ](?:[xh][ .]?26[45]|DDP?5[. ]1)|[. ](?-i:WEB)$|(?:720|1080|2160)p[-. ]WEB[-. ]|[-. ]WEB[-. ](?:720|1080|2160)p|\b\s\/\sWEB\s\/\s\b|(?:AMZN|NF|DP)[. -]WEB[. -](?!Rip))|
```

2022-08-07 20:43 UTC, merged