Fixed: Remove non-functional filters for Trakt Lists
Sonarr/Sonarr pull request #5119
Opened 2022-08-16 21:02 UTC by stevietv

Cherry pick of https://github.com/Radarr/Radarr/commit/5d8775ac96d4b7de1b4381c463e71cf035a3f942

#### Database Migration
NO

#### Description
backport from Radarr reference https://github.com/Radarr/Radarr/issues/7464

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

*

2022-08-20 23:03 UTC, Qstick requested changes

2022-08-20 23:03 UTC, Qstick commented on src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularSettings.cs
> +        [FieldDefinition(2, Label = "Rating", HelpText = "Filter movies by rating range (0-100)")]
not `movies`

2022-08-20 23:03 UTC, Qstick commented on src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularSettings.cs
> +        [FieldDefinition(3, Label = "Certification", HelpText = "Filter movies by a certification (NR,G,PG,PG-13,R,NC-17), (Comma Separated)")]
we don't want `movies` or movie certs

2022-08-20 23:03 UTC, Qstick commented on src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularSettings.cs
> +        [FieldDefinition(4, Label = "Genres", HelpText = "Filter movies by Trakt Genre Slug (Comma Separated) Only for Popular Lists")]
not `movies`

2022-08-20 23:03 UTC, Qstick commented on src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularSettings.cs
> +        [FieldDefinition(5, Label = "Years", HelpText = "Filter movies by year or year range")]
not `movies`

2022-08-21 07:26 UTC, stevietv commented on src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularSettings.cs
> +        [FieldDefinition(2, Label = "Rating", HelpText = "Filter movies by rating range (0-100)")]
edited

2022-08-21 07:26 UTC, stevietv commented on src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularSettings.cs
> +        [FieldDefinition(3, Label = "Certification", HelpText = "Filter movies by a certification (NR,G,PG,PG-13,R,NC-17), (Comma Separated)")]
removed certs filter

2022-08-21 07:26 UTC, stevietv commented on src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularSettings.cs
> +        [FieldDefinition(4, Label = "Genres", HelpText = "Filter movies by Trakt Genre Slug (Comma Separated) Only for Popular Lists")]
edited

2022-08-21 07:26 UTC, stevietv commented on src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularSettings.cs
> +        [FieldDefinition(5, Label = "Years", HelpText = "Filter movies by year or year range")]
edited

2022-09-22 16:48 UTC, merged