Added Discord webhook support for manual interactions.
Sonarr/Sonarr pull request #5200
Opened 2022-10-17 16:33 UTC by StickieBE

#### Database Migration
YES

#### Description
Adds [Discord] webhook support for manual interactions. (e.g.: an episode is downloaded and needs manual import).

**➡️ Updated frontend to include "On Manual Interaction".**

![afbeelding](https://user-images.githubusercontent.com/15276515/196231580-edbfe30d-cc6c-48ad-bacc-549834328449.png)

**➡️ Added Database migration file `#176`.**

**➡️ Added `ImportPendingNotified` TrackedDownloadState.**

**➡️ Added customizable `ManualInteractionFields` Discord settings, similar to the already present `GrabFields` & `ImportFields` (visible when using advanced mode).**

![afbeelding](https://user-images.githubusercontent.com/15276515/196232399-4f1018f6-7be8-47b7-a0df-1ad742987aba.png)

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR
* None that I can think of.

2022-10-17 16:49 UTC, markus101 requested changes
A couple comments to start, but the big thing will be adding support for all notifications, not just Discord.

2022-10-17 16:49 UTC, markus101 commented on src/NzbDrone.Core/Datastore/Migration/176_add_on_manual_interaction_to_notifications.cs
> +    [Migration(176)]
This will need to be changed to 177, an existing PR is already using 176.

2022-10-17 16:49 UTC, markus101 commented on src/NzbDrone.Core/Download/CompletedDownloadService.cs
> +                    trackedDownload.State = TrackedDownloadState.ImportPendingNotified;
I don’t think this should be a separate state, if it needs to be tracked here then a separate property would be more appropriate.

2022-10-17 17:36 UTC, StickieBE commented
> A couple comments to start, but the big thing will be adding support for all notifications, not just Discord.

Exactly, figured I'd get the ball rolling. I primarily use and could test Discord.

2022-12-02 08:36 UTC, StickieBE commented
Will look into adding the other platforms soon-ish. I want this enough to justify the work. 😎

2023-05-08 23:36 UTC, markus101 commented
https://github.com/Sonarr/Sonarr/commit/5ec282750bdea16f770282b80fdaec56a65749e2 implemented everything and fixed up some issues I came across.

2023-05-08 23:36 UTC, closed without merging

2023-05-09 00:50 UTC, austinwbest commented
> [5ec2827](https://github.com/Sonarr/Sonarr/commit/5ec282750bdea16f770282b80fdaec56a65749e2) implemented everything and fixed up some issues I came across.


Reuse of event types without any field to distinguish is not very ideal to services that use the events as switches or to users who will have no clue what the difference is. With download being used twice it has the `isUpgrade` field as a flag at least but unless i missed it the webhook base is literally just reusing the grab event type and no extra fields added?

Why not just give it a unique event type instead of a different event type for custom scripts than webhooks and reusing without being able to tell them apart?

Hopefully i just missed it as this seems quite problematic otherwise. If i did miss it, please point it out as there needs to be some way to implement this logically.

2023-05-09 15:09 UTC, austinwbest commented
> That was purely a copy pasta mistake.

All good, it happens.

> That's the intention, not sure you you'd assume any differently.

Was not an assumption, it is literally the code that was pushed and seen by multiple devs and still merged. So all i did was asked a question about it for clarification. It was clarified in your previous statement of being just a c/p mistake.