Fixed: Chinese release with Season+Abs Eps Number
Sonarr/Sonarr pull request #5356
Opened 2023-01-08 15:59 UTC by zx900930

#### Database Migration
NO

#### Description
Some Chinese release group (Lilith-Raws && LoliHouse) are using Season number + Episode Number in  `Sxx - xx` format, which leads the Parser using Absolute Episode Number instead of Episode Number causing import errors.

#### Test String
`[Lilith-Raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04 - 12 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4`

#### Test String BEFORE patch
`[Lilith-Raws][ Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04][12][Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4`

This patch will normerlize it to SxxExx Format only for these two release groups

#### Test String AFTER patch
`[Lilith-Raws][ Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka ][S04E12][Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4`

#### Trace log for this bug
```
2023-01-08 14:40:43.0|Debug|Parser|Parsing string '[Lilith-Raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04 - 12 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4'
2023-01-08 14:40:43.0|Trace|Parser|Replace regex: ^\[(?<subgroup>[^\]]*?(?:LoliHouse|ZERO|Lilith-Raws)[^\]]*?)\](?<title>[^\[\]]+?)(?: - (?<episode>[0-9-]+)\s*|\[第?(?<episode>[0-9]+(?:-[0-9]+)?)话?(?:END|完)?\])\[
2023-01-08 14:40:43.0|Debug|Parser|Substituted with [Lilith-Raws][ Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04][12][Baha][WEB-DL][1080p][AVC AAC][CHT][MP4]
2023-01-08 14:40:43.0|Trace|Parser|Replace regex: ^\[(?<subgroup>[^\]]+)\](?:\s?★[^\[ -]+\s?)?\[?(?:(?<chinesetitle>[^\]]*?[\u4E00-\u9FCC][^\]]*?)(?:\]\[|\s*[_/·]\s*))?(?<title>[^\]]+?)\]?(?:\[\d{4}\])?\[第?(?<episode>[0-9]+(?:-[0-9]+)?)(?:话|集)?(?:END|完)?\]
2023-01-08 14:40:43.0|Debug|Parser|Substituted with [Lilith-Raws]  Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04 - 12 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4]
2023-01-08 14:40:43.0|Trace|Parser|^\[(?<subgroup>.+?)\][-_. ]?(?<title>[^-]+?)(?:(?<![-_. ]|\b[0]\d+) - )(?:[-_. ]?(?<absoluteepisode>\d{2,3}(\.\d{1,2})?(?!\d+)))+(?:[-_. ]+(?<special>special|ova|ovd))?.*?(?<hash>\[\w{8}\])?(?:$|\.mkv)
2023-01-08 14:40:43.0|Debug|Parser|Episode Parsed. Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04 - 012 
2023-01-08 14:40:43.0|Debug|Parser|Language parsed: Chinese
2023-01-08 14:40:43.0|Debug|QualityParser|Trying to parse quality for [Lilith-Raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04 - 12 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4
2023-01-08 14:40:43.0|Debug|Parser|Quality parsed: WEBDL-1080p v1
2023-01-08 14:40:43.0|Debug|Parser|Release Group parsed: Lilith-Raws
2023-01-08 14:40:43.0|Debug|VideoFileInfoReader|Getting media info from /data/downloads/tv-sonarr/[Lilith-Raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04 - 12 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4
2023-01-08 14:40:43.0|Trace|MediaInfo|Read file offset 0-16384 (16384 bytes)
2023-01-08 14:40:43.0|Trace|MediaInfo|Read file offset 753727881-754613374 (885493 bytes)
2023-01-08 14:40:43.0|Trace|MediaInfo|Read file offset 48-131120 (131072 bytes)
2023-01-08 14:40:43.0|Trace|MediaInfo|Read a total of 1032949 bytes (0.1%)
2023-01-08 14:40:43.0|Debug|ParsingService|Using absolute episode number 12 for: Is It Wrong to Try to Pick Up Girls in a Dungeon? - TVDB: 1x12
```

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

*

2023-01-08 16:27 UTC, markus101 requested changes
This will need tests, similar to the other Unicode releases.

2023-01-08 16:36 UTC, zx900930 commented
> This will need tests, similar to the other Unicode releases.

yes, it still have a minor bug, after fixing it, I'll add TestCase for this patch

2023-01-08 17:34 UTC, stevietv commented
There are some build issues on your added test cases:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	44	Active
Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	45	Active
Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	46	Active
Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	47	Active
Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	48	Active
Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	49	Active
Error	SA1313	Parameter 'SeasonNumber' should begin with lower-case letter	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	50	Active
Error	SA1313	Parameter 'EpisodeNumber' should begin with lower-case letter	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	50	Active
Error	CS1061	'int' does not contain a definition for 'Single' and no accessible extension method 'Single' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	57	Active
```

2023-01-08 17:41 UTC, zx900930 commented
> There are some build issues on your added test cases:
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	44	Active
> Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	45	Active
> Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	46	Active
> Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	47	Active
> Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	48	Active
> Error	SA1001	Commas should be followed by whitespace.	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	49	Active
> Error	SA1313	Parameter 'SeasonNumber' should begin with lower-case letter	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	50	Active
> Error	SA1313	Parameter 'EpisodeNumber' should begin with lower-case letter	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	50	Active
> Error	CS1061	'int' does not contain a definition for 'Single' and no accessible extension method 'Single' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)	Sonarr.Core.Test (net6.0)	e:\Development\stevietv\Sonarr\src\NzbDrone.Core.Test\ParserTests\UnicodeReleaseParserFixture.cs	57	Active
> ```

I'm working on it, missing some references.

2023-01-08 18:59 UTC, zx900930 commented
This shout fix it, all test cases passed.
![image](https://user-images.githubusercontent.com/734749/211213912-bb124cac-56f6-403a-a843-c73ba2118a7d.png)

2023-01-09 06:57 UTC, merged

2023-01-09 06:57 UTC, markus101 commented
Thanks!