New: Improve Manual Import Messaging
Sonarr/Sonarr pull request #5368
Opened 2023-01-13 06:47 UTC by bakerboy448

#### Database Migration
NO

#### Description

Logs at warn that parse is being skipped; previously this was not clearer to the user

#### Todos
- Tests
- Wiki Updates

#### Issues Fixed or Closed by this PR

* https://forums.sonarr.tv/t/sonarr-v4-interactive-manual-import-not-detecting-series/31336

2023-01-13 18:15 UTC, markus101 requested changes
This only improves things if people go an look at the logs,

2023-01-13 18:15 UTC, markus101 commented on src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
> +                    _logger.Warn("Found more than 100 files for multiple series. Skipping parsing.");
It's possible they aren't for multiple series, they're just in a folder that doesn't have a series name so Sonarr doesn't bother parsing them all.

2023-01-13 23:56 UTC, bakerboy448 commented
It's a quick fix that at least communicates it to the users _somewhere_

Best solution would be to have it show in the UI, but not sure on the most optimal way to do that.

2023-01-13 23:57 UTC, bakerboy448 commented on src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
> +                    _logger.Warn("Found more than 100 files for multiple series. Skipping parsing.");
```suggestion
                    _logger.Warn("Found more than 100 files for multiple series or no series. Skipping parsing.");
```

2023-01-21 23:51 UTC, markus101 requested changes

2023-01-21 23:51 UTC, markus101 commented on src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
> +                    _logger.Warn("Found more than 100 files for multiple series or no series. Skipping parsing.");
```suggestion
                    _logger.Warn("Unable to determine series from folder name and found more than 100 files. Skipping parsing");
```

Which should avoid any confusion that it's the file names that matter in this case.

2023-02-04 08:06 UTC, merged