Show calculated (rather than stored) custom format score on season and series history, to match episode history.
Sonarr/Sonarr pull request #5421
Opened 2023-02-08 21:52 UTC by bpoxy

#### Database Migration
NO

#### Description
@markus101 updated episode history to show freshly calculated custom format score (rather than the one stored at time of import) in #5292. However, series and season history still show the stored value. This PR updates series and season to display the freshly calculated score.

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

*

2023-02-08 21:57 UTC, thezoggy commented
if i have x CF setup and it grabbed something. a week later..  lets say made various changes to cf. wouldnt you not want to see what the score was when it grabbed? not what it would be if it was grabbed today.  as history should show the history context..

2023-02-08 22:45 UTC, bpoxy commented
> shouldnt the history show the CF that it was back then? as the current calculated value could be different if CF have been modified. which would get confusing if someone was looking at why something happen while comparing to current values

Personally, I like to see score based on my current rules so that I can determine whether it will be replaced by another release.
I can see the value in seeing the historical score too though, maybe we could show both on the UI? The values are both already accessible.

Currently, the episode and series/season views are different though. I think they should be consistent.

2023-02-10 18:00 UTC, bakerboy448 commented
> Perhaps it makes sense to show the current score on the "Details" tab and the historical score on the "History" tab.

this makes the most sense. History is a snapshot of the point in time.  Details is live

2023-02-11 17:42 UTC, bpoxy commented
> > Perhaps it makes sense to show the current score on the "Details" tab and the historical score on the "History" tab.
> 
> this makes the most sense. History is a snapshot of the point in time. Details is live

There's a few issues with this approach though:
1. All pre-v4 history will have no custom format score to display.
2. The custom formats at the time of grab/import are not stored so a historical score would be shown next to current custom formats.

2023-02-11 18:19 UTC, thezoggy commented
> > > Perhaps it makes sense to show the current score on the "Details" tab and the historical score on the "History" tab.
> > 
> > 
> > this makes the most sense. History is a snapshot of the point in time. Details is live
> 
> There's a few issues with this approach though:
> 
>     1. All pre-v4 history will have no custom format score to display.
> 
>     2. The custom formats at the time of grab/import are not stored so a historical score would be shown next to current custom formats.

1. not sure how that is an issue, CF didnt exist until v4.

2023-02-11 18:31 UTC, bpoxy commented
> 1. not sure how that is an issue, CF didnt exist until v4.

That's a fair point. Personally, I do find it useful to see the scores of the pre-v4 grabs/imports though.
Curious on @markus101's thoughts on this, as he made the initial change.

2023-02-11 20:15 UTC, markus101 commented
My understanding was Radarr showed the latest calculated score in the UI in all places, so my goal was to make that consistent. If that's the case I think keeping it consistent makes the most sense, then show the historic score (from grab/import time) in the details modal/popover. If Radarr doesn't show the current value then maybe we inverse that and show the historic value by default and the calculated value in details.

2023-02-11 20:38 UTC, bpoxy commented
> My understanding was Radarr showed the latest calculated score in the UI in all places, so my goal was to make that consistent. If that's the case I think keeping it consistent makes the most sense, then show the historic score (from grab/import time) in the details modal/popover. If Radarr doesn't show the current value then maybe we inverse that and show the historic value by default and the calculated value in details.

Radarr doesn't seem to show the calculated score anywhere.
The score at time of grab is shown in history along with the current custom formats.
The current custom formats are also shown on the "Files" tab.

I don't like this because (A) the calculated score isn't shown and (B) it seems inconsistent to show the current custom formats with a score that was potentially based on different custom formats.

I propose showing the historical score and historical custom formats in the history views (this would require storing custom format names in history) and showing the calculated score and current custom formats on the "Details" tab.

Thoughts?

2023-02-11 21:16 UTC, markus101 commented
For now let's make it consistent with Radarr, which is what you did originally. We'll discuss if we want to change things later on.

You will need to fix this PR though:

> C:\BuildAgent\work\853acb111afc90d8\frontend\src\Series\History\SeriesHistoryRow.js
[21:56:07 ](https://build.sonarr.tv/buildConfiguration/Sonarr_V4PullRequests_1BuildFrontend/186772?buildTab=log&focusLine=152&logView=flowAware&linesState=152)      79:7  error  'customFormatScore' is missing in props validation  react/prop-types

2023-02-11 21:39 UTC, bpoxy commented
> For now let's make it consistent with Radarr, which is what you did originally. We'll discuss if we want to change things later on.
> 
> You will need to fix this PR though:
> 
> > C:\BuildAgent\work\853acb111afc90d8\frontend\src\Series\History\SeriesHistoryRow.js
> > [21:56:07 ](https://build.sonarr.tv/buildConfiguration/Sonarr_V4PullRequests_1BuildFrontend/186772?buildTab=log&focusLine=152&logView=flowAware&linesState=152)      79:7  error  'customFormatScore' is missing in props validation  react/prop-types

I actually did the opposite of make it consistent with Radarr since Radarr shows only historical score while my change shows calculated score. In order to be consistent with Radarr, we'd have to reject my changes and revert a change you made in https://github.com/Sonarr/Sonarr/pull/5292.

2023-02-12 02:07 UTC, markus101 commented
Radarr changed it recently as well. https://github.com/Radarr/Radarr/commit/cbcf3d1058f47a87c43658084eafac13e7e0889f

2023-02-12 03:44 UTC, bpoxy commented
> Radarr changed it recently as well. [Radarr/Radarr@cbcf3d1](https://github.com/Radarr/Radarr/commit/cbcf3d1058f47a87c43658084eafac13e7e0889f)

Sorry, forgot that I'm not on Radarr's develop branch. :man_facepalming: :sweat_smile:

2023-02-12 03:56 UTC, markus101 requested changes

2023-02-12 03:56 UTC, markus101 commented on frontend/src/Series/History/SeriesHistoryRow.js
> +  customFormatScore: PropTypes.number.isRequired
Put this above `onMarkAsFailedPress`

2023-02-12 22:48 UTC, merged