Check response status code in classes that extend RssParser
Sonarr/Sonarr pull request #5604
Opened 2023-04-30 20:09 UTC by mynameisbogdan

#### Database Migration
NO

2023-04-30 22:19 UTC, Qstick commented
And info on what we are attempting to solve here? Torznab spec indicates we should always get a 200 back, and the exception, 429s are handled in HttpClient.

2023-04-30 22:27 UTC, Qstick commented
Ok, so issues in upstream app/site that cause 500 errors to be returned. We should probably add to NewsnabRssParser as well in that case, as a 500 from Prowlarr or Hydra could also be seen there.

2023-05-01 00:54 UTC, Qstick commented
> I'm thinking if maybe `indexerResponse.HttpResponse.HasHttpError` would be a better condition in case someone likes to use >= 200 <300 codes.

Yea, agree

2023-05-06 17:57 UTC, markus101 requested changes
> Any info on what we are attempting to solve here?

This is why the template asks for this information, please don't nuke it.

2023-05-06 17:57 UTC, markus101 commented on src/NzbDrone.Core/Indexers/EzrssTorrentRssParser.cs
> +            if (indexerResponse.HttpResponse.HasHttpError)
I think we always want to call this, same as we did before to catch HTML content responses.

2023-05-06 18:10 UTC, markus101 commented on src/NzbDrone.Core/Indexers/EzrssTorrentRssParser.cs
> +            if (indexerResponse.HttpResponse.HasHttpError)
I understand, but EZRSS parser always checked this, unless there is a report of an issue then it should continue to do so.

2023-05-06 18:21 UTC, markus101 commented on src/NzbDrone.Core/Indexers/EzrssTorrentRssParser.cs
> +            if (indexerResponse.HttpResponse.HasHttpError)
You don't want to revert it, just don't require an HTTP error to check it here.

2023-05-06 18:31 UTC, markus101 commented on src/NzbDrone.Core/Indexers/EzrssTorrentRssParser.cs
> +            if (indexerResponse.HttpResponse.HasHttpError)
Only for EZRSS, it was the only one previously using `base.PreProcess`

2023-05-07 17:26 UTC, markus101 approved these changes

2023-05-07 17:29 UTC, merged