Added the ability to skip redownload when marking an item as failed in the activity queue
Sonarr/Sonarr pull request #5803
Opened 2023-07-13 19:09 UTC by PearsonFlyer

This code is lifted from Lidarr. When marking an item as failed in the activity queue, a new check-box appears allowing you to skip a re-download search, and just mark it as failed and remove it from the queue instead.

Here is what it looks like before you check the blocklist box:

![image](https://github.com/Sonarr/Sonarr/assets/15488393/e2420305-ff9c-4891-abc0-7f8e12640b70)

And here is what it looks like when you check the blocklist box:

![image](https://github.com/Sonarr/Sonarr/assets/15488393/ea2542d1-3eb4-4db1-a866-f81ad5ab34f9)

Also added the use of translations for these functions.

#### Database Migration
NO

#### Description
Sometimes when you're blocklisting an item, you don't want it to re-search and download the next thing.

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

*

2023-07-13 19:29 UTC, markus101 requested changes
The original Lidarr work has some incorrect variable naming that should probably be resolved, but should be fixed in this PR before landing.

2023-07-13 19:29 UTC, markus101 commented on frontend/src/Activity/Queue/QueueRow.js
> +  onRemoveQueueItemModalConfirmed = (blocklist, skipredownload) => {
This differs from Lidarr, but Lidarr's variable should be renamed. `skipRedownload` (several places this should be changed)

2023-07-13 19:29 UTC, markus101 commented on src/NzbDrone.Core/Download/DownloadFailedEvent.cs
> +        public bool SkipReDownload { get; set; }
`SkipRedownload` is more correct.

2023-07-13 20:51 UTC, jack-mil commented
I like this feature! 
I can also imagine a use case where a user wants to skip a redownload search, but not necessarily add the release to a blocklist. This could be to perform a manual interactive search and select a specific release.

Could the option to skip redownload search be decoupled from adding the release to the blocklist ?

2023-07-14 11:13 UTC, PearsonFlyer commented
All case changes made as requested.

2023-07-15 17:26 UTC, markus101 reviewed
Just one more small thing to change

2023-07-15 17:26 UTC, markus101 commented on frontend/src/Activity/Queue/RemoveQueueItemsModal.js
> +              blocklist &&
Please convert to a ternary: `blocklist ? ... : null`, similar to `allPending` starting at line 100 above.

2023-07-18 02:38 UTC, markus101 commented on package.json
> -    "@types/redux-actions": "2.6.2",
This change needs to be reverted

2023-07-18 12:38 UTC, PearsonFlyer commented on package.json
> -    "@types/redux-actions": "2.6.2",
Done.

2023-07-18 12:46 UTC, PearsonFlyer commented
I merged the develop branch en.json file with my 2 new additions, which should resolve conflicts there.

2023-07-18 20:55 UTC, markus101 commented
The build is failing with some linting issues: https://build.sonarr.tv/buildConfiguration/Sonarr_V4PullRequests_1BuildFrontend/200669?buildTab=log&logView=flowAware&linesState=86.113&focusLine=113

`yarn lint` locally will show the errors as well.

2023-07-20 17:13 UTC, PearsonFlyer commented
> The build is failing with some linting issues: https://build.sonarr.tv/buildConfiguration/Sonarr_V4PullRequests_1BuildFrontend/200669?buildTab=log&logView=flowAware&linesState=86.113&focusLine=113
> 
> `yarn lint` locally will show the errors as well.

Weird, I do lint before building. I am not getting any lint errors at all.

`E:\repos\sonarr\src>yarn lint
yarn run v1.22.19
$ eslint --config frontend/.eslintrc.js --ignore-path frontend/.eslintignore frontend/
Done in 19.07s.`

2023-07-22 03:44 UTC, markus101 commented
Odd, looks like `en.json` has a conflict, so maybe after rebasing it'll be good.

2023-07-23 00:04 UTC, markus101 commented
Turns out trying to fix merge conflicts from GitHub is a disaster, fixed everything up locally and landed in d7025a98deb321397db9a4933cf688b68eafeba9

2023-07-23 00:04 UTC, closed without merging