WIP: Translate settings pages
Sonarr/Sonarr pull request #5836
Opened 2023-07-23 17:18 UTC by stevietv

á#### Database Migration
NO

#### Description
Implementing translations in the frontend settings pages

#### Todos
- [x] Settings page
- [ ] Media Management
- [ ] Profiles
- [ ] Quality
- [x] Custom Formats
- [ ] Indexers
- [x] Download Clients
- [ ] Import Lists
- [ ] Connect
- [ ] Metadata
- [ ] Metadata Source
- [ ] Tags
- [ ] General
- [ ] UI

#### Issues Fixed or Closed by this PR

*

2023-07-30 17:07 UTC, markus101 requested changes
Commented on a few strings that are direct conversions from the english string to a key, I know these came from downstream, but we can improve them and downstream will sync up.

2023-07-30 17:07 UTC, markus101 commented on frontend/src/Settings/Tags/AutoTagging/Specifications/AddSpecificationModalContent.js
> +                  {translate('SonarrSupportsTheFollowingPropertiesForAutoTaggingRules')}
Similar thing here.

2023-07-30 17:07 UTC, markus101 commented on frontend/src/Settings/Tags/AutoTagging/AutoTaggings.js
> +        errorMessage={translate('UnableToLoadAutoTagging')}
`AutoTaggingLoadError` maybe?

2023-07-30 17:07 UTC, markus101 commented on frontend/src/Settings/Quality/Definition/QualityDefinitions.js
> +          errorMessage={translate('UnableToLoadQualityDefinitions')}
`QualityDefinitionsLoadError`?

2023-07-30 17:07 UTC, markus101 commented on frontend/src/Settings/Quality/Definition/QualityDefinition.js
> +                    message={translate('NoMinimumForAnyRuntime')}
This one seems alright despite being a literal conversion.

2023-08-03 11:04 UTC, stevietv commented on frontend/src/Settings/Tags/AutoTagging/Specifications/AddSpecificationModalContent.js
> +              {translate('UnableToAddANewConditionPleaseTryAgain')}
replaced all these with less verbose key

2023-08-03 11:17 UTC, stevietv commented on frontend/src/Settings/Tags/AutoTagging/Specifications/AddSpecificationModalContent.js
> +                  {translate('SonarrSupportsTheFollowingPropertiesForAutoTaggingRules')}
done

2023-08-03 18:59 UTC, markus101 requested changes
There are a few places where we're using capitals for the full acronym instead of following the typical CamelCase naming that we should adjust.

2023-08-03 18:59 UTC, markus101 commented on frontend/src/Settings/CustomFormats/CustomFormats/Specifications/EditSpecificationModalContent.js
> +                  <InlineMarkdown data={translate('ThisConditionMatchesUsingRegularExpressions')} />
This should also be less verbose.

2023-08-03 18:59 UTC, markus101 commented on frontend/src/Settings/General/GeneralSettings.js
> +          message={`${translate('RestartRequiredToApplyChanges')} ${isWindowsService ? translate('RestartRequiredToApplyChangesIsWindowsService') : ''}`}
`RestartRequiredToApplyChangesIsWindowsService` this also seems needlessly verbose

2023-08-03 18:59 UTC, markus101 commented on frontend/src/Settings/General/GeneralSettings.js
> +          cancelLabel={translate('IllRestartLater')}
`RestartLater` should be enough.

2023-08-03 18:59 UTC, markus101 commented on frontend/src/Settings/ImportLists/ImportListExclusions/EditImportListExclusionModalContent.js
> +                <FormLabel>{translate('TVDBID')}</FormLabel>
`TvdbId`

2023-08-03 18:59 UTC, markus101 commented on frontend/src/Settings/ImportLists/ImportListExclusions/EditImportListExclusionModalContent.js
> +                  helpText={translate('TVDBIDExcludeHelpText')}
`TvdbId`

2023-08-03 18:59 UTC, markus101 commented on frontend/src/Settings/Indexers/Indexers/EditIndexerModalContent.js
> +                <FormLabel>{translate('EnableRSS')}</FormLabel>
Rss (same for other uses of `RSS` here)

2023-08-03 18:59 UTC, markus101 commented on frontend/src/Settings/Indexers/Options/IndexerOptions.js
> +              <FormLabel>{translate('RSSSyncInterval')}</FormLabel>
Rss (and others in this file/elsewhere)

2023-08-03 19:50 UTC, stevietv commented on frontend/src/Settings/Indexers/Options/IndexerOptions.js
> +              <FormLabel>{translate('RSSSyncInterval')}</FormLabel>
captured RSS, SSL, UTC, URL and TVDB

2023-08-03 19:57 UTC, stevietv commented
> There are a few places where we're using capitals for the full acronym instead of following the typical CamelCase naming that we should adjust.

Done another pass - the only ones I didn't adjust to camelCase were UI - I believe this one stays capitals as its two letters?

2023-08-03 23:21 UTC, markus101 commented
I think we should do `UI` -> `Ui` as well for consistency, then just needs a rebase.

2023-08-04 10:42 UTC, stevietv commented
UI has been renamed to Ui.
Rebased and translations rechecked.

2023-08-04 17:09 UTC, merged

2023-08-04 17:09 UTC, markus101 commented
Thanks @stevietv!!