New: Add root folder select to EditSeriesModal
Sonarr/Sonarr pull request #5866
Opened 2023-08-01 17:29 UTC by ricci2511

#### Database Migration
NO

#### Description
Simply added the root folder select to the edit series modal. Changing the root folder also changes the series path accordingly.

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Screenshot (if UI related)
![root-folder1](https://github.com/Sonarr/Sonarr/assets/80476005/86fa54cb-fe85-4f8d-a1c9-8b05df34993f)
![root-folder2](https://github.com/Sonarr/Sonarr/assets/80476005/99a70595-2eef-47c9-87ec-248b1a45267c)

#### Issues Fixed or Closed by this PR

* Closes #5544

2023-08-02 00:32 UTC, markus101 requested changes
The fact that you can change both the root folder and the path separately at the same time is going to cause some confusion and likely some issues, especially with how the new path is being updated.

Instead of a drop down a modal that either communicates with the backend and gets the new path given the chosen root folder and series or uses a pre-calculated value, like how it's done in `SeriesLookupController`, but the latter option could lead to a stale value.

2023-08-02 00:32 UTC, markus101 commented on frontend/src/Series/Edit/EditSeriesModalConnector.js
> +  componentDidMount() {
New line after comment

2023-08-02 00:32 UTC, markus101 commented on frontend/src/Series/Edit/EditSeriesModalContent.js
> +                helpText={translate(
This translation needs to be extracted to a key

2023-08-02 00:32 UTC, markus101 commented on frontend/src/Series/Edit/EditSeriesModalContentConnector.js
> +      const newPath = combinePath(isWindows, value, [title]);
Using the series title isn't sufficient, this path needs to be generated on the backend to take the format into account.

2023-08-02 21:50 UTC, ricci2511 commented
Yeah, your concerns make sense. Just one thing, so if the root folder dropdown is ditched in favor of the modal approach how would the expected "user flow" be? Can you maybe provide a really high level example of the SeriesEditModal UI/UX? Just to make sure I understood correctly.

2023-08-02 23:01 UTC, markus101 commented
I think something like `Update Monitoring` when using series selection.

![image](https://github.com/Sonarr/Sonarr/assets/413544/8d56cea9-7c1b-4c60-9bd2-c4208e99afd0)

When the modal is opened the path for the series folder could be constructed, (precomputing could be useful for other things, but it's not a free operation and often not needed).

Once the root folder is chosen we could show the user the new path that will be used like we do in add series:
![image](https://github.com/Sonarr/Sonarr/assets/413544/88983ecf-01be-4fff-958f-a1e501089d8f)

2024-01-14 20:34 UTC, markus101 commented
Closing, but we can reopen once updated.

2024-01-14 20:34 UTC, closed without merging