Improve various messaging for UX
Sonarr/Sonarr pull request #5945
Opened 2023-08-20 00:23 UTC by bakerboy448

#### Database Migration
NO

#### Description

#### Todos
- Tests
- [x] Wiki Updates

#### Issues Fixed or Closed by this PR

*

2023-08-20 18:12 UTC, markus101 requested changes
Do we really want to add `Check your logs for details.` to every health check message?

2023-08-20 18:12 UTC, markus101 commented on src/NzbDrone.Core/Localization/Core/en.json
> +  "DownloadClientRootFolderHealthCheckMessage": "Download client {0} downloads completed downloads in to the root folder {1}. You should not download to the app's Library ('root') folder.",
Too many downloads, `places` is more correct.

`You should not download to the {2}'s root folder.` - where `{2}` is Sonarr/Radarr/Lidarr/etc

2023-08-20 18:12 UTC, markus101 commented on src/NzbDrone.Core/Localization/Core/en.json
> +  "LibraryImportTipsDontUseDownloadsFolder": "Do not use for importing downloads from your download client. This is only for importing existing organized libraries and not unsorted files.",
The `,` is correct, it shouldn't be replaced with `and`

2023-08-20 18:12 UTC, markus101 commented on src/NzbDrone.Core/Localization/Core/en.json
> +  "EnableAutomaticAddHelpText": "Add series from this list to Sonarr when syncs are performed via the UI or as a scheduled app task",
`or automatically via scheduled tasks`

2023-08-20 18:24 UTC, bakerboy448 commented
> Do we really want to add `Check your logs for details.` to every health check message?

given the quantity of users that see the error and are like "what is this" spoonfeeding seems prudent

2023-08-20 23:20 UTC, markus101 commented
If they need to be spoon fed checking logs wouldn't likely be sufficient and they don't need to be fed the same spoon in the same part of the app multiple times. 

Instead of telling the user `n` times to check logs we can put it once in the UI with all the health checks.

2023-08-24 17:05 UTC, bakerboy448 commented
Replaced with https://github.com/Sonarr/Sonarr/issues/5958

2023-08-24 17:05 UTC, closed without merging