Fix: translate for empty appName token
Sonarr/Sonarr pull request #6156
Opened 2023-11-05 09:01 UTC by stevietv

#### Database Migration
NO

#### Description
when there tokens are passed to translate function appName is not added to the list, thus is skipped in multiple translation strings.
translate() function now defaults to it (when no tokens are passed) and adds it when tokens are passed.

#### Todos

#### Issues Fixed or Closed by this PR

* #6155

2023-11-05 09:12 UTC, ZephireNZ commented
Instead of always overriding this field, would it be better to set it only when it's not already set?

2023-11-05 09:14 UTC, stevietv commented
> Instead of always overriding this field, would it be better to set it only when it's not already set?

We always want this field to be set to "Sonarr", there shouldn't be another case where the token doesn't equal Sonarr if passed in.

2023-11-05 09:15 UTC, stevietv commented
oh and @ZephireNZ thanks for spotting the error!!

2023-11-07 01:26 UTC, markus101 requested changes

2023-11-07 01:26 UTC, markus101 commented on frontend/src/Utilities/String/translate.ts
> +  tokens.appName = 'Sonarr';
Should update line 28 to only initialize the object.

2023-11-09 23:54 UTC, markus101 approved these changes

2023-11-10 00:00 UTC, merged