translate backend notifications settings
Sonarr/Sonarr pull request #6227
Opened 2023-12-02 19:58 UTC by stevietv

#### Database Migration
NO

#### Description
translate backend notifications settings and some associated validation responses.

#### Todos

#### Issues Fixed or Closed by this PR

*

2023-12-30 23:51 UTC, markus101 requested changes
Keeping the `Logger` last keeps it consistent with other files, commented on a couple spots, but applies to all of them.

2023-12-30 23:51 UTC, markus101 commented on src/NzbDrone.Core/Notifications/Apprise/AppriseProxy.cs
> +        public AppriseProxy(IHttpClient httpClient, Logger logger, ILocalizationService localizationService)
```suggestion
        public AppriseProxy(IHttpClient httpClient, ILocalizationService localizationService, Logger logger)
```

2023-12-30 23:51 UTC, markus101 commented on src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
> +            ILocalizationService localizationService)
```suggestion
            ILocalizationService localizationService,
            Logger logger)
```

2023-12-31 10:55 UTC, stevietv commented
> Keeping the `Logger` last keeps it consistent with other files, commented on a couple spots, but applies to all of them.

done and rebased

2024-01-02 19:42 UTC, markus101 commented
Needs a small fix for the code formatting:
`.\src\NzbDrone.Core\Notifications\Join\JoinProxy.cs(27,48): error SA1001: Commas should be followed by whitespace`

2024-01-02 19:46 UTC, stevietv commented
> Needs a small fix for the code formatting: `.\src\NzbDrone.Core\Notifications\Join\JoinProxy.cs(27,48): error SA1001: Commas should be followed by whitespace`

fixed! forgot to check back if this one passed the build in all the v4 excitement :D

2024-01-03 20:40 UTC, markus101 approved these changes

2024-01-03 20:41 UTC, merged