Improve Custom Format compare logging
Sonarr/Sonarr pull request #6254
Opened 2023-12-15 22:01 UTC by bakerboy448

#### Database Migration
NO

#### Description
title
#### Todos
- Tests
- Wiki Updates

#### Issues Fixed or Closed by this PR

*

2023-12-16 02:36 UTC, thezak48 commented
`New file's custom formats [{0}] score of [{1}] do not improve on [{2}] score of ({3}), skipping
`
That feels easier to say

2023-12-16 08:43 UTC, stevietv commented
To be consistent with the parenthesis or square brackets

> `New file's custom formats [{0}] score of ({1}) does not improve on [{2}] score of ({3}), skipping ` That feels easier to say

2023-12-19 23:36 UTC, bakerboy448 commented
> To be consistent with the parenthesis or square brackets
> 
> > `New file's custom formats [{0}] score of ({1}) does not improve on [{2}] score of ({3}), skipping `

need to differentiate the CFs vs the score.

Aligned with downstream and added logging for both the decision engine and import

2023-12-20 06:32 UTC, stevietv requested changes
the word 'do' is a bit superfluous.

2023-12-20 06:32 UTC, stevietv commented on src/NzbDrone.Core/DecisionEngine/Specifications/UpgradableSpecification.cs
> +            _logger.Debug("New item's custom formats [{0}] ({1}) do improve on [{2}] ({3}), accepting",
```suggestion
            _logger.Debug("New item's custom formats [{0}] ({1}) improve on [{2}] ({3}), accepting",
```

2023-12-20 06:32 UTC, stevietv commented on src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/UpgradeSpecification.cs
> +                _logger.Debug("New item's custom formats [{0}] ({1}) do improve on [{2}] ({3}), accepting",
```suggestion
                _logger.Debug("New item's custom formats [{0}] ({1}) improve on [{2}] ({3}), accepting",
```

2023-12-20 06:51 UTC, stevietv requested changes

2023-12-20 06:51 UTC, stevietv commented on src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/UpgradeSpecification.cs
> +                        currentFormatScore);
````suggestion
                        newFormats != null ? newFormats.ConcatToString() : "",
                        newFormatScore,
                        currentFormats != null ? currentFormats.ConcatToString() : "",
                        currentFormatScore);
````

2023-12-20 06:51 UTC, stevietv commented on src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/UpgradeSpecification.cs
>              }
```suggestion
                        newFormats != null ? newFormats.ConcatToString() : "",
                        newFormatScore,
                        currentFormats != null ? currentFormats.ConcatToString() : "",
                        currentFormatScore);
```

2023-12-20 06:51 UTC, stevietv commented
the null check will fix the failing tests in the build.

2023-12-20 10:00 UTC, bakerboy448 commented
Preciate the null fixups! :)

2023-12-28 19:17 UTC, markus101 approved these changes

2023-12-28 20:35 UTC, merged