Added Bluray576p Quality
Sonarr/Sonarr pull request #6267
Opened 2023-12-23 04:52 UTC by Voyex

#### Database Migration
YES

#### Description
Added the 

#### Todos
- [ x ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

*  #6203

2023-12-23 05:09 UTC, Voyex commented on src/NzbDrone.Core/Datastore/Migration/201_add_bluray576_quality_in_profile.cs
> +                if (profile.Id == 1 || profile.Id == 2)
Thank you, I appreciate the input. I was unsure which would be safer.

2023-12-23 06:46 UTC, thezoggy commented on src/NzbDrone.Core.Test/Qualities/QualityFixture.cs
> +                        new object[] { 6, Quality.Bluray720p },
typo?

2023-12-31 00:28 UTC, markus101 requested changes

2023-12-31 00:28 UTC, markus101 commented on src/NzbDrone.Core/Datastore/Migration/201_add_bluray576_quality_in_profile.cs
> +    }
```suggestion
        public string Name { get; set; }
        public int? Quality { get; set; }
        public bool Allowed { get; set; }
        public List<ProfileItem201> Items { get; set; }
    }
```

2023-12-31 00:28 UTC, markus101 commented on src/NzbDrone.Core/Datastore/Migration/201_add_bluray576_quality_in_profile.cs
> +                    updateProfileCmd.CommandText = "UPDATE QualityProfiles SET Name = ?, Cutoff = ?, Items = ? WHERE Id = ?";
These queries are invalid for Postgres, you'll need to mirror the existing migrations and correctly quote the columns/table names.

2023-12-31 00:28 UTC, markus101 commented on src/NzbDrone.Core/Datastore/Migration/201_add_bluray576_quality_in_profile.cs
> +                getProfilesCmd.CommandText = @"SELECT Id, Name, Cutoff, Items FROM QualityProfiles";
Same here.

2024-05-05 02:08 UTC, markus101 commented
Closing based on the comments in the issue.

2024-05-05 02:08 UTC, closed without merging