Sort Custom Filters
Sonarr/Sonarr pull request #6335
Opened 2024-01-11 20:09 UTC by stevietv

#### Database Migration
NO

#### Description
Sorts custom filters alphabetically

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

* closes #6334

2024-01-12 00:28 UTC, markus101 requested changes
We also need to sort them in filter menu

2024-01-12 06:52 UTC, stevietv commented
> We also need to sort them in filter menu

done! I missed that as every time I checked the list they were already sorted due to the state being sorted (coming from the modal)

I also added a separator here to split standard from custom filters. Helps a little to distinguish why there are two lists.

2024-01-16 04:36 UTC, markus101 approved these changes
Just the suggestion to make it a ternary, but will commit that change and land once CI is happy.

2024-01-16 04:36 UTC, markus101 commented on frontend/src/Components/Menu/FilterMenuContent.js
> +            <MenuItemSeparator />
```suggestion
          customFilters.length > 0 ?
            <MenuItemSeparator /> :
            null
```

2024-01-16 05:53 UTC, merged