Fix: Wrap routeableipv4 in try catch
Sonarr/Sonarr pull request #6644
Opened 2024-03-22 09:33 UTC by covert8

#### Description
Wrap NetworkInterface.GetAllNetworkInterfaces in try catch to solve race condition on aarch64

#### Database Migration
NO

#### Issues Fixed or Closed by this PR
* Closes #
https://github.com/Prowlarr/Prowlarr/issues/2076

2024-03-23 00:01 UTC, markus101 approved these changes
Should we log anything so people know what's going on without having to dig into code?

2024-03-24 08:48 UTC, covert8 commented
Sounds like a good idea

2024-03-25 01:04 UTC, markus101 requested changes
Converting these methods to non-static seems reasonable, shouldn't make too much of an impact over all.

2024-03-25 01:04 UTC, markus101 commented on src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs
> +                    _logger.Info("Fallback to ipv4, disabling ipv6: {routableIPv4}");
```suggestion
                    _logger.Info("IPv4 is available: {0}, IPv6 will be {1}", routableIPv4, routableIPv4 ? "disabled", "left enabled");
```

2024-03-25 01:04 UTC, markus101 commented on src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs
> +                _logger.Debug("Caught exception while GetAllNetworkInterfaces assuming IPv4 connectivity");
Be worth logging the exception too.

2024-03-25 01:04 UTC, markus101 commented on src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs
> +                _logger.Trace("HasRoutableIPv4Address: " + e.Message);
I don't think we need to log this separately, could append to the debug message.

2024-03-25 01:04 UTC, markus101 commented on src/NzbDrone.Core.Test/Framework/CoreTest.cs
> +            Mocker.SetConstant<IHttpDispatcher>(new ManagedHttpDispatcher(Mocker.Resolve<IHttpProxySettingsProvider>(), Mocker.Resolve<ICreateManagedWebProxy>(), Mocker.Resolve<ICertificateValidation
```suggestion
            Mocker.SetConstant<IHttpDispatcher>(new ManagedHttpDispatcher(Mocker.Resolve<IHttpProxySettingsProvider>(), Mocker.Resolve<ICreateManagedWebProxy>(), Mocker.Resolve<ICertificateValidationService>(), Mocker.Resolve<UserAgentBuilder>(), Mocker.Resolve<CacheManager>(), Mocker.Resolve<IHttpDispatcher>(), TestLogger));
```

2024-03-27 15:45 UTC, markus101 approved these changes

2024-03-28 05:31 UTC, merged