New: Expose log size limit to API and WebUI
Sonarr/Sonarr pull request #7111
Opened 2024-08-17 12:24 UTC by martylukyy

#### Description
This PR exposes the newly added LogSizeLimit from this commit https://github.com/Sonarr/Sonarr/commit/813965e6a20edef2772d68eaa7646af33028425a to the API and the WebUI.
Translations for EN and DE have been added and the German translation file has been sorted alphabetically.

#### Screenshots for UI Changes

![image](https://github.com/user-attachments/assets/ffd8a222-2d64-45cb-9b87-d6e27a3f5a2e)

#### Proposals

While fiddling this together i noticed that the log size limit has a hardcoded upper limit of 10 MB.
https://github.com/Sonarr/Sonarr/blob/cd3a1c18ab4f8b644ddea3e6358ec23eb3069526/src/NzbDrone.Core/Configuration/ConfigFileProvider.cs#L245
Is there a specific reason for that limit or could this be subject to change?

2024-08-17 13:30 UTC, martylukyy commented
> You should undo the non-en translations as it's going to break weblate and would require a reset to make it work again.
> 
> Considering we only support values from 1 to 10, we should have validation for this?

Done and done. Thanks for your help. Appreciate it!

Do you have any insights on the consensus to raise the log size limit?

2024-08-17 15:38 UTC, martylukyy commented
So more than a few times i found myself looking through my trace logs to debug something only to find out the thing i am looking for is not in the most recent trace log but in the one before.
Funny enough i even needed both logs once to see what was the matter.

I can see your point though and maybe this should be an advanced setting (as bogdan said) to prevent the situation you mentioned.

Personally, i don't see a reason not to raise the hard limit to something bigger if it's within reason and keep the default.
I wouldn't set the hard limit so high that your editor / IDE crashes from loading one file but big enough so i don't need to put all my recent logs files in a folder and CTRL SHIFT F through it with an IDE.
Somewhere from 30 to 50 for the upper limit would be reasonable if you want my opinion.
If you are worried about space constrictions maybe decrease the number of logs kept? (Just brainstorming here)

To add to the "Why do we need this in the UI?" part:
Otherwise i would need to go edit the file via SSH/FTP in case the above mentioned situation happens and it's kinda a pity you need to do this since sonarr has all the things you need to debug from the WebUI.

2024-08-17 17:02 UTC, bakerboy448 commented
Definitely should be an advanced option and need to expand the description and maybe we should show the total usage based on the selected log level and log file quantity? Or just show total usage for input value denoted by each possibly log level and the log file quantity?

Use case would be as stated not having to comb multiple trace logs to get all relevant pieces, primarily during scans, rss, or searches for debugging

2024-08-17 17:39 UTC, markus101 requested changes
Definitely an advanced setting. For now let's stick with the 10 MB limit, in a future version we can consider changing the default/maximum/total number of files.

2024-08-17 17:39 UTC, markus101 commented on src/NzbDrone.Core/Localization/Core/en.json
> +  "LogSizeLimitHelpText": "Sets the size in MB above which log files will be automatically archived.",
Maybe something like:
```suggestion
  "LogSizeLimitHelpText": "Maximum log file size in MB before archiving. Default is 1MB",
```

2024-08-17 17:39 UTC, markus101 commented on frontend/src/Settings/General/LoggingSettings.js
> +          name="logSizeLimit"
```suggestion
          max={10}
          min={1}
          name="logSizeLimit"
```

2024-08-17 17:39 UTC, markus101 commented on frontend/src/Settings/General/LoggingSettings.js
> +
```suggestion

      <FormGroup>
        <FormLabel>{translate('LogSizeLimit')}</FormLabel>
```

2024-08-17 18:33 UTC, martylukyy commented
Implemented your suggestions.
Need to look into why i cannot make it an advanced setting...
When i set the advancedSettings prop i just disappears 🤔

2024-08-17 19:03 UTC, martylukyy commented
Thanks - now i feel stupid 😂 
I was missing the part in GeneralSettings.js 😅

2024-08-19 01:59 UTC, markus101 approved these changes
Thanks for the fixes

2024-08-19 01:59 UTC, merged