New: Add headers in webhook connection
Sonarr/Sonarr pull request #7371
Opened 2024-11-06 23:41 UTC by gauthier-th

#### Description
This PR adds a new field to add custom headers in the webhook connection. It uses a TextTagInput to store each value.
However, this TextTagInput has a drawback: it makes it impossible to have a header value with a comma, but I haven't figured out a cleaner/simpler way of implementing it.

#### Screenshots for UI Changes
![image](https://github.com/user-attachments/assets/d47ab17e-7cb9-4d35-9949-da01bffeb9cb)

#### Database Migration
NO

#### Issues Fixed or Closed by this PR
* Fix https://github.com/Radarr/Radarr/issues/10552
* Re https://github.com/Radarr/Radarr/pull/10651

2024-11-08 06:19 UTC, markus101 commented
Maybe something like https://github.com/Sonarr/Sonarr/blob/f8a879f4c1a1ef1fb4df915d8308af07114f0422/frontend/src/Components/Form/KeyValueListInput.js ?

It used to be used for preferred words and would need to be re-added and converted to typescript, but would fill in well for headers being key/value pairs.

2024-11-10 00:34 UTC, gauthier-th commented
> Maybe something like https://github.com/Sonarr/Sonarr/blob/f8a879f4c1a1ef1fb4df915d8308af07114f0422/frontend/src/Components/Form/KeyValueListInput.js ?
> 
> It used to be used for preferred words and would need to be re-added and converted to typescript, but would fill in well for headers being key/value pairs.

Yes, it's better this way.

![image](https://github.com/user-attachments/assets/739792f2-fae2-49c9-9a8c-b8d690d941b4)

2024-11-14 04:38 UTC, markus101 requested changes
Looking pretty good, mostly just naming and small clean up to do

2024-11-14 04:38 UTC, markus101 commented on frontend/src/Components/Form/KeyValueListInput.tsx
> +  const onItemChange = useCallback(
No need for these comments and use `handle` instead of `on` for callbacks

```suggestion
  const handleItemChange = useCallback(
```

2024-11-14 04:38 UTC, markus101 commented on frontend/src/Components/Form/KeyValueListInput.tsx
> +      }
New lines around if/else block

```suggestion

      if (index === null) {
        newValue.push(itemValue);
      } else {
        newValue.splice(index, 1, itemValue);
      }

```

2024-11-14 04:38 UTC, markus101 commented on frontend/src/Components/Form/KeyValueListInput.tsx
> +  const onRemoveItem = useCallback(
Same thing here

2024-11-14 04:38 UTC, markus101 commented on frontend/src/Components/Form/KeyValueListInput.tsx
> +  // Render component
No need for this either

2024-11-14 04:38 UTC, markus101 commented on frontend/src/Components/Form/KeyValueListInput.tsx
> +      if (v.key || v.value) acc.push(v);
```suggestion
      if (v.key || v.value) {
        acc.push(v);
      }
```

2024-11-14 04:38 UTC, markus101 commented on frontend/src/Components/Form/KeyValueListInputItem.tsx
> +        {!isNew && (
Use ternary, ```isNew ? null : (```

2024-11-14 04:38 UTC, markus101 commented on frontend/src/Components/Form/KeyValueListInputItem.tsx
> +    () => onRemove(index),
Since it's not going to be on a single line

```suggestion
    () => { 
      onRemove(index),
    }
```

2024-11-14 04:38 UTC, markus101 commented on frontend/src/Components/Form/KeyValueListInputItem.tsx
> +  // Handler for key change
No need for these comments either

2024-11-14 04:38 UTC, markus101 commented on frontend/src/Components/Form/KeyValueListInput.tsx
> +  onChange: (updatedValue: { name: string; value: KeyValue[] }) => void;
```suggestion
  onChange: InputOnChange<KeyValue[]>;
```

2024-11-15 03:00 UTC, markus101 approved these changes

2024-11-15 03:01 UTC, merged